# Section 7.1

## Question 1
```SQL

Select modelyear,make,model
from EVRegistry;

```
## Question 2 
```SQL

SELECT ElectricVehicleType
FROM EVRegistry; 

```
## Question 3
```SQL

SELECT *
FROM EVRegistry
WHERE ElectricVehicleType = 'Battery Electric Vehicle (BEV)' 

```
## Question 4
```SQL

SELECT Make,Model, BaseMSRP
FROM EVRegistry
WHERE BaseMSRP BETWEEN 20000 and 35000
ORDER by 3 DESC 

```

# Section 7.2

## Question 1
```SQL

SELECT *
FROM EVRegistry
WHERE City is NULL

```
## Question 2 
```SQL

SELECT Make,Model,ElectricVehicleType, VIN
FROM EVRegistry
WHERE VIN like '%3E1EA1J'

```
## Question 3
```SQL

SELECT ModelYear,Make,Model,ElectricVehicleType,ElectricRange
FROM EVRegistry
WHERE Make IN ('TESLA','CHEVROLET')
ORDER by Make, ModelYear DESC

```
## Question 4
```SQL

SELECT stationId, count(*) as usage
FROM EVCharging
GROUP by stationId
ORDER by usage DESC
LIMIT 5

```
## Question 5
```SQL

SELECT userId, 
min(chargeTimeHrs) as 'minhrs',
max(chargeTimeHrs) as 'maxhrs'
FROM EVCharging
WHERE chargeTimeHrs > 0.5
GROUP by stationId
ORDER by 2,3

```

# Section 7.3

## Question 1
```SQL

SELECT weekday,
round(avg(chargeTimeHrs),2) as 'hrs'
FROM EVCharging
GROUP by weekday
ORDER by 'hrs' DESC

Wednesday

```
## Question 2 
```SQL

SELECT userId,
round(sum(kwhTotal),2) as 'totalpower'
FROM EVCharging
GROUP by userId
order by 2 DESC
LIMIT 15

```
## Question 3
```SQL

SELECT FacilityKey,
facilityID,
typeFacility,
count(stationId) as 'numstation'
FROM factCharge
INNER JOIN dimFacility
ON factCharge.facilityID = dimFacility.FacilityKey
GROUP by typeFacility
ORDER by 4 DESC 

```
## Question 4


Primary Key: Contain unique values, no NULL values

Foreign Key: A field in on table, refering to primary key in another

## Question 5
```SQL

SELECT userId, 
min(chargeTimeHrs) as 'minhrs',
max(chargeTimeHrs) as 'maxhrs'
FROM EVCharging
GROUP by userId
HAVING chargeTimeHrs > 1.0
ORDER by 2,3 DESC 

```